# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/playwright:v1.63.0@sha256:eff16c30e6f3f4af0a03fa4b706120d5e9b0891c344a27d64559aff5900a4a27

WORKDIR /workspace
COPY tests/e2e/package.json tests/e2e/package-lock.json ./
RUN npm ci --ignore-scripts
COPY tests/e2e/ ./

ENV PLAYWRIGHT_BASE_URL=http://web
CMD ["npm", "test", "--", "--project=chromium", "--project=firefox", "--project=webkit"]
